import { ProductModel } from "../store/types";

export const products: ProductModel[] = [
  {
    type:"Planta",
    quantity: 10,
    id: "1",
    img: "https://multimidia.gazetadopovo.com.br/media/info/2017/201710/plantas-problemas-saudavel.png",
    name: "Planta Artifical",
    price: "19.99",
    description: "A planta artifical é ótima para a casa, proporcionando...",
  },
  {
    type:"Flor",
    quantity: 10,
    id: "2",
    img: "https://www.rosabrancafloricultura.com.br/wp-content/uploads/2019/12/botao-rosa-pink.jpg.png", 
    name: "Rosa cor-de-rosa",
    price: "19.99",
    description: "A rosa cor-de-rosa é ótima para presentear...",
  },
  {
    type:"Flor",
    quantity: 10,
    id: "3",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6m26YdavEqLgTPLebFN4KqYSUWXoVj6WTZA&usqp=CAU", 
    name: "Rosa vermelha",
    price: "18.99",
    description: "A rosa vermelha é ótima para primeiros encontros...",
  },
  {
    type:"Buque",
    quantity: 10,
    id: "4",
    img: "https://www.uniflores.com.br/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/b/u/buque-12-rosas-vermelhas1_2.jpg",    
    name: "Buquê de rosas vermelhas",
    price: "99.99",
    description: "O buquê de rosas vermelhas é ideal para pedir em casamento...",
  },
  {
    type:"Buque",
    quantity: 10,
    id: "5",
    img: "https://www.uniflores.com.br/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/b/u/buque-charme-em-rosas2.jpg",
    name: "Buquê cor-de-rosa",
    price: "89.99",
    description: "O buquê cor-de-rosa de é delicado, ideal para ...",
  },
  {
    type:"Planta",
    quantity: 10,
    id: "6",
    img: "https://imagens-revista.vivadecora.com.br/uploads/2019/02/O-Lirio-da-paz-decora-a-mesa-lateral.jpg",
    name: "Lírio da Paz",
    price: "19.99",
    description: "O lírio da paz é um ótimo purificador para a casa...",
  },
  {
    type:"Vaso",
    quantity: 10,
    id: "7",
    img: "https://static3.tcdn.com.br/img/img_prod/475075/vaso_decorativo_planta_podocarpus_verde_13cm_23325_1_20201213202627.jpg",
    name: "Vaso pequeno para casa",
    price: "39.99",
    description: "Vaso pequeno perfeito para colocar em janelas",
  },
  {
    type:"Vaso",
    quantity: 10,
    id: "8",
    img: "https://cdn.awsli.com.br/600x450/1190/1190687/produto/45176329/fdeb8e7991.jpg",
    name: "Vaso com Palmeira",
    price: "49.99",
    description: "O vaso com a palmeira é do tamanho ideal mesmo depois que a palmeira crescer.",
  },
  {
    type:"Planta",
    quantity: 10,
    id: "9",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa1liH1gJQb6F9dIYMGP4tdZQYtYUMTaOfLA&usqp=CAU",
    name: "Jiboia",
    price: "49.99",
    description: "A jiboia é uma planta ótima",
  },
  
  

]